# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    ubuntu14:
      containerImage: ubuntu:14.04
    ubuntu16:
      containerImage: ubuntu:16.04
    ubuntu18:
      containerImage: ubuntu:18.04

container: $[ variables['containerImage'] ]

resources:
  repositories:
    - repository: templates
      type: git
      name: testing
      ref: refs/tags/v1.0

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  - script: printenv
  # - script: echo ${{ resources.repositories['self'].name }}
  # - script: echo ${{ resources.repositories['self'].defaultBranch }}
  # - script: echo ${{ resources.repositories['self'].versionInfo.author }}
  # - script: echo ${{ job.steps }}
  # - script: echo ${{ task.id }}

